<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.64.0" />
    <PackageReference Include="Google.Protobuf" Version="3.27.2" />
    <PackageReference Include="Grpc.AspNetCore.Web" Version="2.64.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="../../LatticeSDK/protos/**/*.proto" GrpcServices="None" ProtoRoot="../../LatticeSDK/protos" />
    <Protobuf Update="../../LatticeSDK/protos/anduril/entitymanager/v1/entity_manager_api.pub.proto" GrpcServices="Server" />
    <Protobuf Update="../../LatticeSDK/protos/anduril/taskmanager/v1/task_manager_api.pub.proto" GrpcServices="Server" />
  </ItemGroup>


</Project>
